services:
  localstack:
    image: localstack/localstack:3.8
    container_name: medical-rag-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: ecr,ecs,iam,logs,sts,elbv2
      DEBUG: "0"
      PERSISTENCE: "1"
      AWS_DEFAULT_REGION: ap-southeast-1
      LS_LOG: warn
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry:2
    container_name: medical-rag-registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  localstack_data:
  registry_data:
